define: &HOLDING_INSTITUTION_AS_RECORDED P5
define: &SHELFMARK                       P8
define: &LINK_TO_INSTITUTIONAL_RECORD    P9
define: &TITLE_AS_RECORDED               P10
define: &UNIFORM_TITLE_AS_RECORDED       P12
define: &ASSOCIATED_NAME_AS_RECORDED     P14
define: &GENRE_AS_RECORDED               P18
define: &SUBJECT_AS_RECORDED             P19
define: &LANGUAGE_AS_RECORDED            P21
define: &PRODUCTION_DATE_AS_RECORDED     P23
define: &DATED                           P26
define: &PRODUCTION_PLACE_AS_RECORDED    P27
define: &PHYSICAL_DESCRIPTION            P29
define: &MATERIAL_AS_RECORDED            P30
define: &NOTE                            P32
define: &ACKNOWLEDGEMENTS                P33
define: &IIIF_MANIFEST                   P41

HOLDING_INSTITUTION_AS_RECORDED:
  transformer_class: InstitutionClaimTransformer
SHELFMARK:
  transformer_class: ShelfmarkClaimTransformer
LINK_TO_INSTITUTIONAL_RECORD:
  transformer_class: InstitutionalRecordClaimTransformer
TITLE_AS_RECORDED:
  transformer_class: TitleClaimTransformer
UNIFORM_TITLE_AS_RECORDED:
  transformer_class: UniformTitleClaimTransformer
ASSOCIATED_NAME_AS_RECORDED:
  transformer_class: NameClaimTransformer
GENRE_AS_RECORDED:
  transformer_class: TermClaimTransformer
SUBJECT_AS_RECORDED:
  transformer_class: TermClaimTransformer
LANGUAGE_AS_RECORDED:
  transformer_class: LanguageClaimTransformer
PRODUCTION_DATE_AS_RECORDED:
  transformer_class: DateClaimTransformer
DATED:
  transformer_class: DatedClaimTransformer
PRODUCTION_PLACE_AS_RECORDED:
  transformer_class: PlaceClaimTransformer
PHYSICAL_DESCRIPTION:
  transformer_class: PhysicalDescriptionClaimTransformer
MATERIAL_AS_RECORDED:
  transformer_class: MaterialClaimTransformer
NOTE:
  transformer_class: NoteClaimTransformer
ACKNOWLEDGEMENTS:
  transformer_class: AcknowledgementsClaimTransformer
IIIF_MANIFEST:
  transformer_class: IiifManifestClaimTransformer
