P5:
  transformer_class: InstitutionClaimTransformer
P8:
  transformer_class: ShelfmarkClaimTransformer
P9:
  transformer_class: InstitutionalRecordClaimTransformer
P10:
  transformer_class: TitleClaimTransformer
P12:
  transformer_class: UniformTitleClaimTransformer
P14:
  transformer_class: NameClaimTransformer
P18:
  transformer_class: TermClaimTransformer
P19:
  transformer_class: TermClaimTransformer
P21:
  transformer_class: LanguageClaimTransformer
P23:
  transformer_class: DateClaimTransformer
P26:
  transformer_class: DatedClaimTransformer
P27:
  transformer_class: PlaceClaimTransformer
P29:
  transformer_class: PhysicalDescriptionClaimTransformer
P30:
  transformer_class: MaterialClaimTransformer
P32:
  transformer_class: NoteClaimTransformer
P33:
  transformer_class: AcknowledgementsClaimTransformer
P41:
  transformer_class: IiifManifestClaimTransformer
