P5:
  type: qualified
  prefix: institution
  fields:
    - display
    - search
    - facet
  authority: P4
P8:
  type: unqualified
  prefix: shelfmark
  fields:
    - display
    - search
P9:
  type: link
  prefix: institutional_record
  fields:
    - link
P10:
  type: qualified
  prefix: title
  fields:
    - display
    - search
    - facet
  authority: P11
  fallback: true
P12:
  type: unqualified
  prefix: uniform_title
  fields:
    - search
# NOTE: P14 can translate to any of a few different Solr fields with prefixes derived from the
# value of its role (P15) qualifier. It is handled in its own dedicated processing method.
P14:
  type: qualified
  fields:
    - display
    - search
    - facet
  fallback: true
P18:
  type: qualified
  prefix: term
  fields:
    - display
    - search
    - facet
  authority: P20
  fallback: true
P19:
  type: qualified
  prefix: term
  fields:
    - display
    - search
    - facet
  authority: P20
  fallback: true
P21:
  type: qualified
  prefix: language
  fields:
    - display
    - search
    - facet
  authority: P22
P23:
  type: qualified
  prefix: date
  fields:
    - meta
    - display
    - search
    - facet
  authority: P24
P26:
  type: unqualified
  prefix: dated
  fields:
    - facet
P27:
  type: qualified
  prefix: place
  fields:
    - display
    - search
    - facet
  authority: P28
P29:
  type: unqualified
  prefix: physical_description
  fields:
    - display
    - search
P30:
  type: qualified
  prefix: material
  fields:
    - display
    - search
    - facet
  authority: P31
P32:
  type: unqualified
  prefix: note
  fields:
    - display
    - search
P33:
  type: unqualified
  prefix: acknowledgements
  fields:
    - display
P41:
  type: link
  prefix: iiif_manifest
  fields:
    - facet
    - link
