# frozen_string_literal: true

module DigitalScriptorium
  class SolrDocument
    attr_accessor :qid_meta,
                  :institution_display,
                  :institution_search,
                  :institution_facet,
                  :holding_status_display,
                  :shelfmark_display,
                  :shelfmark_search,
                  :id,
                  :id_display,
                  :id_search,
                  :title_display,
                  :title_search,
                  :title_facet,
                  :author_display,
                  :author_search,
                  :author_facet,
                  :scribe_display,
                  :scribe_search,
                  :scribe_facet,
                  :owner_display,
                  :owner_search,
                  :owner_facet,
                  :language_display,
                  :language_search,
                  :language_facet,
                  :date_meta,
                  :date_display,
                  :date_search,
                  :date_facet,
                  :century_int,
                  :earliest_int,
                  :latest_int,
                  :dated_display,
                  :dated_facet,
                  :place_display,
                  :place_search,
                  :place_facet,
                  :physical_description_display,
                  :physical_description_search,
                  :note_display,
                  :note_search,
                  :acknowledgements_display
  end
end
